#!/usr/bin/env bash

set -e

# Set graphviz path
PATH=/app/graphviz/bin:$PATH

# All requirements of wsgi.py
pip install static

# Needed to serve the application (Procfile)
pip install waitress

pip install -r ${BUILD_DIR}/requirements.txt

# Build Sphinx documentation
(cd ${BUILD_DIR} && make apidoc html)
